apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2-mfe-x-{{ .Values.version | replace "." "-" }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app2-mfe-x-{{ .Values.version | replace "." "-" }}
  template:
    metadata:
      labels:
        app: app2-mfe-x-{{ .Values.version | replace "." "-" }}
    spec:
      containers:
        - name: app2-mfe-x-{{ .Values.version | replace "." "-" }}
          image: 495599745704.dkr.ecr.ap-southeast-2.amazonaws.com/app2-mfe-x:{{ .Values.version }}
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: app2-mfe-x-{{ .Values.version | replace "." "-" }}
  labels:
    app: app2-mfe-x-{{ .Values.version | replace "." "-" }}
spec:
  type: ClusterIP
  selector:
    app: app2-mfe-x-{{ .Values.version | replace "." "-" }}
  ports:
    - name: http
      port: 80
      targetPort: 80
